config/routes.rb
Rails.application.routes.draw do
  resources :journals
  get 'pages/blah', to: 'pages#blah'
# DISCOVERY
  get 'discovery/srog'
  get 'discovery/rfp', to: 'discovery#rfp'
  get 'discovery/frog_e'
  get 'discovery/frog_g'
  get 'discovery/rfa'
  get 'discovery/depo_pmk'
  get 'discovery/depo_indiv'
  get 'discovery/sep_statement'
  get 'discovery/proposed_order'
  get 'discovery/notice_of_motion'
  get 'discovery/atty_decl'
  get 'discovery/memo_panda'
#resources :jcfs
  resources :client_lawsuits
  resources :attorney_lawsuits
  resources :attorneys
  resources :lawsuits

  resources :ncfs
  root "pages#home"
  resources :clients
# lawsuits
 get 'lawsuits/ulawsuits' 
# Scrapes
 get 'scrapes/index', to: 'scrapes#index'
 get 'scrapes/view'

 # Judicial Counsel Forms, jcfs
 get 'jcfs/cms'
 get 'jcfs/frog_general'
 get 'jcfs/frog_employment'
 get 'jcfs/rfa'
 get 'jcfs/pes' # pos_electronic
 get 'jcfs/ex_parte'
 get 'jcfs/dismissal'
  

 # Admin 
  get 'admin/index'
  get 'admin/stored_lawsuits', to: 'admin#stored_lawsuits'
  get '/search', to: 'admin#search'
 
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  get "pages/clt"
  get "pages/ul"
  get "pages/case_info"
  get "pages/cltenvelope"
  get "pages/attyenvelope"
  get 'pages/attycorres'

# Pleadings 
  get 'pleadings/generic', to: 'pleadings#generic'
  get 'pleadings/supp_interrogatories', to: 'pleadings#supp_interrogatories'
  get 'pleadings/decl_atty', to: 'pleadings#decl_atty'

# Responses
  get 'responses/verification', to: 'responses#verification'



end

app/models/lawsuit.rb
class Lawsuit < ApplicationRecord
  belongs_to :user

  has_many :attorney_lawsuits
  has_many :attorneys, through: :attorney_lawsuits

  has_many :client_lawsuits
  has_many :clients, through: :client_lawsuits
  
  has_many :journals

end

app/controllers/lawsuits_controller.rb
class LawsuitsController < ApplicationController
  before_action :set_lawsuit, only: %i[ show edit update destroy ]

  # GET /lawsuits or /lawsuits.json
  def index
    @lawsuits = Lawsuit.all
  end

  # GET /lawsuits/1 or /lawsuits/1.json
  def show
  end

  # GET /lawsuits/new
  def new
    @lawsuit = Lawsuit.new
  end

  # GET /lawsuits/1/edit
  def edit
  end

  # POST /lawsuits or /lawsuits.json
  def create
    @lawsuit = Lawsuit.new(lawsuit_params)

    respond_to do |format|
      if @lawsuit.save
        format.html { redirect_to lawsuit_url(@lawsuit), notice: "Lawsuit was successfully created." }
        format.json { render :show, status: :created, location: @lawsuit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lawsuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lawsuits/1 or /lawsuits/1.json
  def update
    respond_to do |format|
      if @lawsuit.save(lawsuit_params)
        format.html { redirect_to lawsuit_url(@lawsuit), notice: "Lawsuit was successfully updated." }
        format.json { render :show, status: :ok, location: @lawsuit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lawsuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lawsuits/1 or /lawsuits/1.json
  def destroy
    @lawsuit.destroy

    respond_to do |format|
      format.html { redirect_to lawsuits_url, notice: "Lawsuit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lawsuit
      @lawsuit = Lawsuit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lawsuit_params
      params.require(:lawsuit).permit(:user_id, :active, :case_number, :case_title, :date_filed, :cmc, :judge_name,
                :judge_dept, :case_status, :last_roa, :plt_caption, :def_caption, :trial, :trc, :discovery_cutoff,
                :first_expert_exchange, :second_expert_exchange)
    end
end

app/helpers/lawsuits_helper.rb
module LawsuitsHelper
end

app/views/lawsuits/_form.html.erb
<div class="container-fluid">

<%= form_with(model: lawsuit) do |form| %>
  <% if lawsuit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lawsuit.errors.count, "error") %> prohibited this lawsuit from being saved:</h2>

      <ul>
        <% lawsuit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.label :case_number, style: "display: block" %>
    <%= form.text_field :case_number %>
  </div>

  <div>
    <%= form.label :case_title, style: "display: block" %>
    <%= form.text_field :case_title %>
  </div>

  <div>
    <%= form.label :date_filed, style: "display: block" %>
    <%= form.date_field :date_filed %>
  </div>

  <div>
    <%= form.label :cmc, style: "display: block" %>
    <%= form.date_field :cmc %>
  </div>

  <div>
    <%= form.label :judge_name, style: "display: block" %>
    <%= form.text_field :judge_name %>
  </div>

  <div>
    <%= form.label :judge_dept, style: "display: block" %>
    <%= form.text_field :judge_dept %>
  </div>

  <div>
    <%= form.label :case_status, style: "display: block" %>
    <%= form.text_field :case_status %>
  </div>

  <div>
    <%= form.label :last_roa, style: "display: block" %>
    <%= form.text_field :last_roa %>
  </div>

  <div>
    <%= form.label :plt_caption, style: "display: block" %>
    <%= form.text_field :plt_caption %>
  </div>

  <div>
    <%= form.label :def_caption, style: "display: block" %>
    <%= form.text_field :def_caption %>
  </div>

  <div>
    <%= form.label :atty_for, style: "display: block" %>
    <%= form.text_field :atty_for %>
  </div>
  <div>
    <%= form.label :plaintiff, style: "display: block" %>
    <%= form.text_field :plaintiff %>
  </div>
  <div>
    <%= form.label :defendant, style: "display: block" %>
    <%= form.text_field :defendant %>
  </div>

  <div>
    <%= form.label :trial, style: "display: block" %>
    <%= form.date_field :trial %>
  </div>
  <div>
    <%= form.label :trc, style: "display: block" %>
    <%= form.date_field :trc %>
  </div>

   <div>
    <%= form.label :discovery_cutoff, style: "display: block" %>
    <%= form.date_field :discovery_cutoff %>
    </div>

  <div>
    <%= form.label :first_expert_exchange, style: "display: block" %>
    <%= form.date_field :first_expert_exchange %>
  </div>
   <div>
    <%= form.label :second_expert_exchange, style: "display: block" %>
    <%= form.date_field :second_expert_exchange %>
  </div>


</div>

<br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

</div>

app/views/lawsuits/_lawsuit.html.erb
<div id="<%= dom_id lawsuit %>">
  
  <p>
    <strong>Case number:</strong>
    <%= lawsuit.case_number %>
  </p>

  <p>
    <strong>Case title:</strong>
    <%= lawsuit.case_title %>
  </p>

  <p>
    <strong>Date filed:</strong>
    <%= lawsuit.date_filed %>
  </p>



<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Case No.</th>
      <th scope="col">Case Title</th>
      <th scope="col">Filed</th>
    </tr>
    <tbody>
      <tr>
        <th scope="row"><%= @lawsuit.number %></th>
        <td><%= @lawsuit.case_title %></td>
        <td><%= @lawsuit.date_filed %></td>
      </tr>
    </tbody>
  
</table>








</div>

app/views/lawsuits/edit.html.erb
<h1>Editing lawsuit</h1>

<%= render "form", lawsuit: @lawsuit %>

<br>

<div>
  <%= link_to "Show this lawsuit", @lawsuit %> |
  <%= link_to "Back to lawsuits", lawsuits_path %>
</div>

app/views/lawsuits/index.html.erb
<div class="container-fluid">

<p style="color: green"><%= notice %></p>

   <% @lawsuits.each do |i| %>

      <%= link_to i.case_title, lawsuit_path(i) %> 
      <%= i.case_number %><br> 

   <% end %>



</div>

app/views/lawsuits/new.html.erb
<h1>New lawsuit</h1>

<%= render "form", lawsuit: @lawsuit %>

<br>

<div>
  <%= link_to "Back to lawsuits", lawsuits_path %>
</div>

app/views/lawsuits/show.html.erb
<p style="color: green"><%= notice %></p>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Case No.</th>
      <th scope="col">Case Title</th>
      <th scope="col">Filed</th>
      <th scope="col">Judge</th>
    </tr>
    <tbody>
      <tr>
        <td><%= @lawsuit.case_number %></td>
        <td><%= @lawsuit.case_title %></td>
        <% if @lawsuit.date_filed %>
          <td><%= @lawsuit.date_filed.strftime('%m-%d-%Y') %></td>
        <% end %> 
        <td><%= @lawsuit.judge_name %></td>
      </tr>


      <tr>
        <td><strong>Dates:</strong></td>
      </tr>


      <tr>
        <td>Trial Call:
            <% if @lawsuit.trial.present? %>
              <%= @lawsuit.trial.strftime('%m-%d-%Y') %>
            <% else %>
            Not set
            <% end %> 
        </td>

        <td>30 Days Before Trial: 
             <% if @lawsuit.trial.present? %>
              <%= (@lawsuit.trial - 30).strftime('%m-%d-%Y') %>
            <% else %>
            Not set
            <% end %> 
        </td>


      <tr>
        <td>Trial Readiness Conference:
            <% if @lawsuit.trc.present? %>
              <%= @lawsuit.trc.strftime('%m-%d-%Y') %>
            <% else %>
            Not set
            <% end %> 
        </td>
      </tr>

      <tr>
        <td>Discovery CutOff:
            <% if @lawsuit.discovery_cutoff.present? %>
              <%= @lawsuit.discovery_cutoff.strftime('%m-%d-%Y') %>
            <% else %>
            Not set
            <% end %> 
        </td>

        <td>105 Days Before Trial: 
            <% if @lawsuit.trial.present? %>
              <%= (@lawsuit.trial - 105).strftime('%m-%d-%Y') %>
              <% end %> 
        </td>
          
        </tr>

        <tr>
          <td>
            <td>35 Days Before MSJ:
              <% if @lawsuit.trial.present? %>
                <%= (@lawsuit.trial - 140).strftime('%m-%d-%Y') %>
                <% end %> 
          </td>
          </td>
        </tr>

        <tr>
            <td>
                <td>30 Days Before CutOff:
                  <% if @lawsuit.discovery_cutoff.present? %>
                      <%= (@lawsuit.discovery_cutoff - 30).strftime('%m-%d-%Y') %>
                      <% end %> 
                </td>
            </td>
        </tr>


        <tr>
          <td><strong> Counsel: </strong></td>
           
        </tr>
        <tr>
           <td><% @lawsuit.attorney_lawsuits.each do |i| %>
              <%= link_to "#{Attorney.find(i.Attorney_id).name}", attorney_path(i.Attorney_id) %> <%= i.role %>
              <% end %>
            </td>
        </tr>

    </tbody>
  
</table>
<br>
<div class="container-fluid">
  <%= link_to "New Journal Entry", new_journal_path(@lawsuit), class:"btn btn-primary" %> 
  <%= link_to "Journal", pages_blah_path(@lawsuit), class:"btn btn-primary" %> 
</div>

<br>
<div>
  <%= link_to "Edit this lawsuit", edit_lawsuit_path(@lawsuit) %> |
  <%= link_to "Back to lawsuits", lawsuits_path %>

  <%= button_to "Destroy this lawsuit", @lawsuit, method: :delete, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
</div>
<br>
<footer>
<!-- <div class="fixed-bottom"> -->
    <div class="container-fluid">
        <div class="btn-group dropup">
          <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Pleadings
          </button>
          
          <ul class="dropdown-menu">
            <li><%= link_to "Generic Pleading", pleadings_generic_path(@lawsuit), class:'dropdown-item' %></li>
            <li><%= link_to "Proof of Service", "#", class:'dropdown-item' %></li>
            <li><%= link_to "Declaration - Atty", pleadings_decl_atty_path(@lawsuit), class:'dropdown-item' %></li>
          </ul>
        </div>

        <div class="btn-group dropup">
          <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Judicial Counsel Forms
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "CMC Statement", jcfs_cms_path(@lawsuit), class:'dropdown-item' %></li>
            <li><%= link_to "Ex Parte App", jcfs_ex_parte_path(@lawsuit), class:'dropdown-item' %></li>
            <li><%= link_to "Request for Dismissal", jcfs_dismissal_path(@lawsuit), class:'dropdown-item' %></li>
            <li><%= link_to "Proof of Electronic Service", jcfs_pes_path(@lawsuit), class:'dropdown-item' %></li>
          </ul>
        </div>

        <div class="btn-group dropup">
          <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Correspondence
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "Envelope", "Z", class:'dropdown-item' %></li>
            <li><%= link_to "Ltr - Generic", "#", class:'dropdown-item' %></li>
            <li><%= link_to "Ltr to OC", "#", class:'dropdown-item' %></li>
            <li><%= link_to "Meet and Confer", "#", class:'dropdown-item' %></li>
            <li><%= link_to "Something else", "#", class:'dropdown-item' %></li>
          </ul>
        </div>

        <div class="btn-group dropup">
          <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Discovery
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "Supp Interrogatories", pleadings_supp_interrogatories_path(@lawsuit), class:'dropdown-item' %></li>
            <li><%= link_to "Frog-General", jcfs_frog_general_path(@lawsuit), class:'dropdown-item' %></li>
            <li><%= link_to "Frog-Employment", jcfs_frog_employment_path(@lawsuit), class:'dropdown-item' %></li>
            <li><%= link_to "RFAs", jcfs_rfa_path(@lawsuit), class:'dropdown-item' %></li>
            <li><%= link_to "Special Interrogatories", discovery_srog_path(@lawsuit), class:'dropdown-item' %></li>
            <li><%= link_to "Document Production", discovery_rfp_path(@lawsuit), class:'dropdown-item' %></li>
          </ul>
        </div>

        <div class="btn-group dropup">
          <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Responses
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "Verification", responses_verification_path(@lawsuit), class:'dropdown-item' %></li>
          </ul>
          <ul class="dropdown-menu">
            <li><%= link_to "Resp RFP", "#", class:'dropdown-item' %></li>
          </ul>
        </div>


        <div class="btn-group dropup">
          <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Law and Motion
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "Notice of Motion", discovery_notice_of_motion_path(@lawsuit), class: 'dropdown-item' %></li>
            <li><%= link_to "Memo P and A", discovery_memo_panda_path(@lawsuit), class:'dropdown-item' %></li>
            <li><%= link_to "MTC Separate Statement", discovery_sep_statement_path(@lawsuit), class:'dropdown-item' %></li>
             <li><%= link_to "Decl of Attorney", discovery_atty_decl_path(@lawsuit), class:'dropdown-item' %></li>
            <li><%= link_to "[Proposed] Order", discovery_proposed_order_path(@lawsuit), class: 'dropdown-item' %></li>
          </ul>
        </div>

        <div class="btn-group dropup">
          <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Depositions
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "PMK Deposition Notice", "#", class: 'dropdown-item' %></li>
            <li><%= link_to "Individual Depo Notice", discovery_memo_panda_path(@lawsuit), class:'dropdown-item' %></li>
            <li><%= link_to "Subpoena", "#", class: 'dropdown-item' %></li>
            
          </ul>
        </div>



    </div><br>
<!-- </div> -->
</footer>