config/routes.rb
Rails.application.routes.draw do
  resources :journals
  get 'pages/blah', to: 'pages#blah'
# DISCOVERY
  get 'discovery/srog'
  get 'discovery/rfp', to: 'discovery#rfp'
  get 'discovery/frog_e'
  get 'discovery/frog_g'
  get 'discovery/rfa'
  get 'discovery/depo_pmk'
  get 'discovery/depo_indiv'
  get 'discovery/sep_statement'
  get 'discovery/proposed_order'
  get 'discovery/notice_of_motion'
  get 'discovery/atty_decl'
  get 'discovery/memo_panda'
#resources :jcfs
  resources :client_lawsuits
  resources :attorney_lawsuits
  resources :attorneys
  resources :lawsuits

  resources :ncfs
  root "pages#home"
  resources :clients
# lawsuits
 get 'lawsuits/ulawsuits' 
# Scrapes
 get 'scrapes/index', to: 'scrapes#index'
 get 'scrapes/view'

 # Judicial Counsel Forms, jcfs
 get 'jcfs/cms'
 get 'jcfs/frog_general'
 get 'jcfs/frog_employment'
 get 'jcfs/rfa'
 get 'jcfs/pes' # pos_electronic
 get 'jcfs/ex_parte'
 get 'jcfs/dismissal'
  

 # Admin 
  get 'admin/index'
  get 'admin/stored_lawsuits', to: 'admin#stored_lawsuits'
  get '/search', to: 'admin#search'
 
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  get "pages/clt"
  get "pages/ul"
  get "pages/case_info"
  get "pages/cltenvelope"
  get "pages/attyenvelope"
  get 'pages/attycorres'

# Pleadings 
  get 'pleadings/generic', to: 'pleadings#generic'
  get 'pleadings/supp_interrogatories', to: 'pleadings#supp_interrogatories'
  get 'pleadings/decl_atty', to: 'pleadings#decl_atty'

# Responses
  get 'responses/verification', to: 'responses#verification'



end

app/views/shared/_admin_nav.html.erb
<div class="container-fluid">
	<%= link_to "Lawsuits - Stored", scrapes_index_path, class:"btn btn-success" %>
	<%= link_to "Something else", "Z", class:"btn btn-success" %>
	<%= link_to "New Case Filings", ncfs_path, class:"btn btn-primary" %>
	<%= link_to "Parser", pages_case_info_path %> 


</div>

app/views/shared/_nav.html.erb
   
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg bg-dark">
      <div class="container-fluid">
        <%= link_to image_tag("logo"), root_path %>
        <a class="navbar-brand" style="color: green;" href="#">Law Office of Zachary T. Tyson</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            
            <li class="nav-item">
              <%= link_to "Lawsuits", lawsuits_path, class:"btn btn-success" %>
            </li>

            <li>
                <%= link_to "Clients", clients_path, class:"btn btn-info" %>
            </li>

            <li>
                <%= link_to "Attorneys", attorneys_path, class:"btn btn-warning" %>
            </li>


            <li>
                <%= link_to "User-Lawsuits", pages_ul_path, class:"btn btn-outline-success" %>
            </li>

            
                <li>
                    <%= link_to "Admin", admin_index_path, class:"btn btn-secondary" %>
                </li>
        



            <li>
                <%= button_to "Log Out", destroy_user_session_path, method: :delete, class:"btn btn-danger position-absolute top-5 end-0"  %>
            </li>

          </ul>
          
        </div>
      </div>
    </nav>
</div>

app/views/shared/_sdcalendar.html.erb
<div class="accordion" id="accordionPanelsStayOpenExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne">
        San Diego Superior Court - Calendar Search
      </button>
    </h2>
    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse">
      <div class="accordion-body">
        <strong><%= @loc %></strong><br> 
       
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
        New Case Filings
      </button>
    </h2>
    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse">
      <div class="accordion-body">
        <strong><%= @yo %></strong>
      </div>
    </div>
  </div>
  
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
        ROA Updates
      </button>
    </h2>
    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse">
      <div class="accordion-body">
        <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
        OE WT Cases on Calendar
      </button>
    </h2>
    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse">
      <div class="accordion-body">
        <%= @tada %>
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
        Trials on Calendar Today
      </button>
    </h2>
    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse">
      <div class="accordion-body">
        <% @trial_cal.each do |i| %>
          <li><%= i %></li>
        <% end %>
      </div>
    </div>
  </div>
 
</div>