config/routes.rb
Rails.application.routes.draw do
  resources :journals
  get 'pages/blah', to: 'pages#blah'
# DISCOVERY
  get 'discovery/srog'
  get 'discovery/rfp', to: 'discovery#rfp'
  get 'discovery/frog_e'
  get 'discovery/frog_g'
  get 'discovery/rfa'
  get 'discovery/depo_pmk'
  get 'discovery/depo_indiv'
  get 'discovery/sep_statement'
  get 'discovery/proposed_order'
  get 'discovery/notice_of_motion'
  get 'discovery/atty_decl'
  get 'discovery/memo_panda'
#resources :jcfs
  resources :client_lawsuits
  resources :attorney_lawsuits
  resources :attorneys
  resources :lawsuits

  resources :ncfs
  root "pages#home"
  resources :clients
# lawsuits
 get 'lawsuits/ulawsuits' 
# Scrapes
 get 'scrapes/index', to: 'scrapes#index'
 get 'scrapes/view'

 # Judicial Counsel Forms, jcfs
 get 'jcfs/cms'
 get 'jcfs/frog_general'
 get 'jcfs/frog_employment'
 get 'jcfs/rfa'
 get 'jcfs/pes' # pos_electronic
 get 'jcfs/ex_parte'
 get 'jcfs/dismissal'
  

 # Admin 
  get 'admin/index'
  get 'admin/stored_lawsuits', to: 'admin#stored_lawsuits'
  get '/search', to: 'admin#search'
 
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  get "pages/clt"
  get "pages/ul"
  get "pages/case_info"
  get "pages/cltenvelope"
  get "pages/attyenvelope"
  get 'pages/attycorres'

# Pleadings 
  get 'pleadings/generic', to: 'pleadings#generic'
  get 'pleadings/supp_interrogatories', to: 'pleadings#supp_interrogatories'
  get 'pleadings/decl_atty', to: 'pleadings#decl_atty'

# Responses
  get 'responses/verification', to: 'responses#verification'



end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user

  enum status: [:active, :inactive]

  has_many :client_lawsuits
  has_many :lawsuits, through: :client_lawsuits

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:user_id, :status, :fname, :mname, :lname, :dob, :ssn, :address, :city, :state, :zip, :email, :phone, :ec_name, :ec_phone, :ec_email, :dln)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">

  <div class="container-fluid">
  
      <table class="table-primary table-striped table-hover">
        
        <thead>
          <tr class="table-primary">
              <th scope="col">Name </th>
              <th scope="col">Phone</th>
              <th scope="col">Email</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>
              <%= link_to "#{client.lname}, #{client.fname}", pages_clt_path(client) %>
            </td>
            <td>
              <%= client.phone %>
            </td>
            <td>
              <%= client.email %>
              
            </td>
          </tr>



      <tr> 
          <td><%= client.fname %> <%= client.lname %><td>
      </tr>


        </tbody>

      </table>


  </div>

</div>

app/views/clients/_form.html.erb
<div class="container-fluid">

    <%= form_with(model: client) do |form| %>
      <% if client.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

          <ul>
            <% client.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :user_id, style: "display: block" %>
        <%= form.text_field :user_id %>
      </div>

      <div>
        <%= form.label :status, style: "display: block" %>
        <%= form.select :status, options_for_select(Client.statuses.map {|k,v| [k]}) %>
      </div>

      <div>
        <%= form.label :fname, style: "display: block" %>
        <%= form.text_field :fname %>
      </div>

      <div>
        <%= form.label :mname, style: "display: block" %>
        <%= form.text_field :mname %>
      </div>

      <div>
        <%= form.label :lname, style: "display: block" %>
        <%= form.text_field :lname %>
      </div>

      <div>
        <%= form.label :dob, style: "display: block" %>
        <%= form.text_field :dob %>
      </div>

      <div>
        <%= form.label :ssn, style: "display: block" %>
        <%= form.text_field :ssn %>
      </div>

      <div>
        <%= form.label :address, style: "display: block" %>
        <%= form.text_field :address %>
      </div>

      <div>
        <%= form.label :city, style: "display: block" %>
        <%= form.text_field :city %>
      </div>

      <div>
        <%= form.label :state, style: "display: block" %>
        <%= form.text_field :state %>
      </div>

      <div>
        <%= form.label :zip, style: "display: block" %>
        <%= form.text_field :zip %>
      </div>

      <div>
        <%= form.label :email, style: "display: block" %>
        <%= form.text_field :email %>
      </div>

      <div>
        <%= form.label :phone, style: "display: block" %>
        <%= form.text_field :phone %>
      </div>

      <div>
        <%= form.label :ec_name, style: "display: block" %>
        <%= form.text_field :ec_name %>
      </div>

      <div>
        <%= form.label :ec_phone, style: "display: block" %>
        <%= form.text_field :ec_phone %>
      </div>

      <div>
        <%= form.label :ec_email, style: "display: block" %>
        <%= form.text_field :ec_email %>
      </div>

      <div>
        <%= form.label :dln, style: "display: block" %>
        <%= form.text_field :dln %>
      </div>

      <div>
        <%= form.submit %>
      </div>
    <% end %>

</div>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>


<div class="container-fluid">
    <h3>Clients</h3>

    <div id="clients">
      <% @clients.each do |client| %>
        <%= render client %>
      <% end %>
    </div><br>


    <%= link_to "New client", new_client_path, class:"btn btn-info" %>
</div>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Last Name.</th>
      <th scope="col">First Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
     
    </tr>
    <tbody>
      <tr>
        <td><%= @client.lname %></td>
        <td><%= @client.fname %></td>
        <td><%= @client.phone %></td>
        <td><%= @client.email %></td>

      </tr>


      <tr> 
        <td><%= @client.fname %> <%= @client.lname %><td>
      </tr>




    </tbody>
  
</table>
<br>
<hr>
<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>