config/routes.rb
Rails.application.routes.draw do
  resources :journals
  get 'pages/blah', to: 'pages#blah'
# DISCOVERY
  get 'discovery/srog'
  get 'discovery/rfp', to: 'discovery#rfp'
  get 'discovery/frog_e'
  get 'discovery/frog_g'
  get 'discovery/rfa'
  get 'discovery/depo_pmk'
  get 'discovery/depo_indiv'
  get 'discovery/sep_statement'
  get 'discovery/proposed_order'
  get 'discovery/notice_of_motion'
  get 'discovery/atty_decl'
  get 'discovery/memo_panda'
#resources :jcfs
  resources :client_lawsuits
  resources :attorney_lawsuits
  resources :attorneys
  resources :lawsuits

  resources :ncfs
  root "pages#home"
  resources :clients
# lawsuits
 get 'lawsuits/ulawsuits' 
# Scrapes
 get 'scrapes/index', to: 'scrapes#index'
 get 'scrapes/view'

 # Judicial Counsel Forms, jcfs
 get 'jcfs/cms'
 get 'jcfs/frog_general'
 get 'jcfs/frog_employment'
 get 'jcfs/rfa'
 get 'jcfs/pes' # pos_electronic
 get 'jcfs/ex_parte'
 get 'jcfs/dismissal'
  

 # Admin 
  get 'admin/index'
  get 'admin/stored_lawsuits', to: 'admin#stored_lawsuits'
  get '/search', to: 'admin#search'
 
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  get "pages/clt"
  get "pages/ul"
  get "pages/case_info"
  get "pages/cltenvelope"
  get "pages/attyenvelope"
  get 'pages/attycorres'

# Pleadings 
  get 'pleadings/generic', to: 'pleadings#generic'
  get 'pleadings/supp_interrogatories', to: 'pleadings#supp_interrogatories'
  get 'pleadings/decl_atty', to: 'pleadings#decl_atty'

# Responses
  get 'responses/verification', to: 'responses#verification'



end

app/models/attorney.rb
class Attorney < ApplicationRecord

	has_many :attorney_lawsuits
	has_many :lawsuits, through: :attorney_lawsuits

end

app/controllers/attorneys_controller.rb
class AttorneysController < ApplicationController
  before_action :set_attorney, only: %i[ show edit update destroy ]

  # GET /attorneys or /attorneys.json
  def index
    @attorneys = Attorney.all
  end

  # GET /attorneys/1 or /attorneys/1.json
  def show
  end

  # GET /attorneys/new
  def new
    @attorney = Attorney.new
  end

  # GET /attorneys/1/edit
  def edit
  end

  # POST /attorneys or /attorneys.json
  def create
    @attorney = Attorney.new(attorney_params)

    respond_to do |format|
      if @attorney.save
        format.html { redirect_to attorney_url(@attorney), notice: "Attorney was successfully created." }
        format.json { render :show, status: :created, location: @attorney }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attorney.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attorneys/1 or /attorneys/1.json
  def update
    respond_to do |format|
      if @attorney.update(attorney_params)
        format.html { redirect_to attorney_url(@attorney), notice: "Attorney was successfully updated." }
        format.json { render :show, status: :ok, location: @attorney }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attorney.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attorneys/1 or /attorneys/1.json
  def destroy
    @attorney.destroy

    respond_to do |format|
      format.html { redirect_to attorneys_url, notice: "Attorney was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attorney
      @attorney = Attorney.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attorney_params
      params.require(:attorney).permit(:sbn, :status, :name, :firm, :address, :city, :state, :zip, :phone, :email)
    end
end

app/helpers/attorneys_helper.rb
module AttorneysHelper
end

app/views/attorneys/_attorney.html.erb
<div id="<%= dom_id attorney %>">
  <p>
    <strong>Sbn:</strong>
    <%= attorney.sbn %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= attorney.status %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= attorney.name %>
  </p>

  <p>
    <strong>Firm:</strong>
    <%= attorney.firm %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= attorney.address %>
  </p>

  <p>
    <strong>City:</strong>
    <%= attorney.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= attorney.state %>
  </p>

  <p>
    <strong>Zip:</strong>
    <%= attorney.zip %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= attorney.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= attorney.email %>
  </p>

</div>

app/views/attorneys/_form.html.erb
<%= form_with(model: attorney) do |form| %>
  <% if attorney.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attorney.errors.count, "error") %> prohibited this attorney from being saved:</h2>

      <ul>
        <% attorney.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sbn, style: "display: block" %>
    <%= form.text_field :sbn %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :firm, style: "display: block" %>
    <%= form.text_field :firm %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :zip, style: "display: block" %>
    <%= form.text_field :zip %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/attorneys/edit.html.erb
<h1>Editing attorney</h1>

<%= render "form", attorney: @attorney %>

<br>

<div>
  <%= link_to "Show this attorney", @attorney %> |
  <%= link_to "Back to attorneys", attorneys_path %>
</div>

app/views/attorneys/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid">

    <h3>Attorneys</h3>

    <div id="attorneys">
      <% @attorneys.each do |attorney| %>
        <%= link_to attorney.name, attorney %> <%= attorney.firm %><br>

      <% end %>
    </div>
    <br>
    <%= link_to "New attorney", new_attorney_path, class:"btn btn-warning" %>


</div>

app/views/attorneys/new.html.erb
<h1>New attorney</h1>

<%= render "form", attorney: @attorney %>

<br>

<div>
  <%= link_to "Back to attorneys", attorneys_path %>
</div>

app/views/attorneys/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid">

    <%= render @attorney %>
<br>
<hr>
     <%= link_to "Envelope", pages_attyenvelope_path(@attorney), class: "btn btn-warning" %>
     <%= link_to "Letter", pages_attycorres_path(@attorney), class: "btn btn-warning" %>
<br>    
<hr>
    <div>
      <%= link_to "Edit this attorney", edit_attorney_path(@attorney) %> |
      <%= link_to "Back to attorneys", attorneys_path %>

      <%= button_to "Destroy this attorney", @attorney, method: :delete %>
    </div>



</div>